import os
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd
def setup_plot_style():
    """
    Establish the project-wide visualization standard.
    Uses standard Seaborn styling which produces clean, readable white-background 
    cards that embed well into the dark HTML report.
    """
    # Enforce standard Seaborn aesthetic (matching Phase 1 and 2 implicit defaults)
    sns.set_theme(style="whitegrid", palette="deep")
    
    # Enforce standard white background for figures so they appear as cohesive cards
    plt.rcParams.update({
        'figure.facecolor': 'white',
        'axes.facecolor': 'white',
        'savefig.facecolor': 'white',
        'savefig.edgecolor': 'none',
        'savefig.dpi': 300,
        'savefig.bbox': 'tight'
    })

def save_plot(fig, output_dir: str, filename: str):
    """
    Standardized plot export function to be used across all phases.
    Ensures consistent DPI, background, and bounding box behavior.
    """
    os.makedirs(output_dir, exist_ok=True)
    fig.tight_layout()
    fig.savefig(os.path.join(output_dir, filename))
    plt.close(fig)

def get_compound_palette(compounds) -> dict:
    """
    Returns a deterministic color palette for a given list of tyre compounds.
    Recognized compounds get their canonical F1 color.
    Unrecognized compounds get a deterministic fallback color generated by hashing.
    """
    canonical_colors = {
        'SOFT': '#ef4444',
        'MEDIUM': '#eab308',
        'HARD': '#ffffff',
        'INTERMEDIATE': '#22c55e',
        'WET': '#3b82f6',
        'ULTRASOFT': '#b24c96',
        'SUPERSOFT': '#da291c',
        'HYPERSOFT': '#f2a9c3',
        'UNKNOWN': '#9ca3af'
    }
    
    fallback_colors = sns.color_palette("husl", 20).as_hex()
    palette = {}
    
    for c in compounds:
        if pd.isna(c) or c is None:
            continue
        c_str = str(c).upper()
        if c_str in canonical_colors:
            palette[c] = canonical_colors[c_str]
        else:
            # Deterministic hash-based fallback
            hash_val = sum(ord(char) for char in c_str)
            palette[c] = fallback_colors[hash_val % len(fallback_colors)]
            
    return palette
